"""esquema inicial

Revision ID: 695648a525ed
Revises: 
Create Date: 2026-09-28 23:47:51.776533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '695648a525ed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parametro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor_combustivel_litro', sa.Double(), nullable=False),
    sa.Column('km_por_litro_padrao', sa.Double(), nullable=False),
    sa.Column('custo_adicional_km', sa.Double(), nullable=False),
    sa.Column('jornada_padrao_horas', sa.Double(), nullable=False),
    sa.Column('tempo_minimo_parada_min', sa.Double(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parametro'))
    )
    op.create_table('ponto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=120), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Double(), nullable=True),
    sa.Column('longitude', sa.Double(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ponto'))
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('senha_hash', sa.String(length=200), nullable=False),
    sa.Column('perfil', sa.Enum('ADMIN', 'GERENTE', 'MOTORISTA', name='perfil', native_enum=False, length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario'))
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_email', sa.String(length=160), nullable=True),
    sa.Column('entidade', sa.String(length=40), nullable=False),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=10), nullable=False),
    sa.Column('antes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('depois', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_auditoria_usuario_id_usuario'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auditoria'))
    )
    op.create_index(op.f('ix_auditoria_criado_em'), 'auditoria', ['criado_em'], unique=False)
    op.create_index('ix_auditoria_entidade', 'auditoria', ['entidade', 'entidade_id'], unique=False)
    op.create_table('gerente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('cargo', sa.String(length=40), nullable=False),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_gerente_usuario_id_usuario'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gerente')),
    sa.UniqueConstraint('usuario_id', name=op.f('uq_gerente_usuario_id'))
    )
    op.create_table('motorista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('documento', sa.String(length=30), nullable=True),
    sa.Column('veiculo', sa.String(length=80), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=True),
    sa.Column('km_por_litro', sa.Double(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('anonimizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gerente_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gerente_id'], ['gerente.id'], name=op.f('fk_motorista_gerente_id_gerente'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_motorista_usuario_id_usuario'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_motorista')),
    sa.UniqueConstraint('usuario_id', name=op.f('uq_motorista_usuario_id'))
    )
    op.create_index(op.f('ix_motorista_gerente_id'), 'motorista', ['gerente_id'], unique=False)
    op.create_table('roteiro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PLANEJADO', 'EM_ANDAMENTO', 'CONCLUIDO', name='statusroteiro', native_enum=False, length=20), nullable=False),
    sa.Column('distancia_total_km', sa.Double(), nullable=False),
    sa.Column('distancia_manual', sa.Boolean(), nullable=False),
    sa.Column('tempo_total_parado_min', sa.Double(), nullable=False),
    sa.Column('custo_por_km', sa.Double(), nullable=False),
    sa.Column('custo_estimado', sa.Double(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['motorista_id'], ['motorista.id'], name=op.f('fk_roteiro_motorista_id_motorista'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roteiro'))
    )
    op.create_index('ix_roteiro_data_motorista', 'roteiro', ['data', 'motorista_id'], unique=False)
    op.create_table('ponto_roteiro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roteiro_id', sa.Integer(), nullable=False),
    sa.Column('ponto_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('chegada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('saida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('chegada_lat', sa.Double(), nullable=True),
    sa.Column('chegada_lng', sa.Double(), nullable=True),
    sa.Column('saida_lat', sa.Double(), nullable=True),
    sa.Column('saida_lng', sa.Double(), nullable=True),
    sa.Column('tempo_parado_min', sa.Double(), nullable=True),
    sa.ForeignKeyConstraint(['ponto_id'], ['ponto.id'], name=op.f('fk_ponto_roteiro_ponto_id_ponto'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['roteiro_id'], ['roteiro.id'], name=op.f('fk_ponto_roteiro_roteiro_id_roteiro'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ponto_roteiro')),
    sa.UniqueConstraint('roteiro_id', 'ordem', deferrable=True, initially='DEFERRED', name='uq_ponto_roteiro_ordem')
    )
    op.create_index(op.f('ix_ponto_roteiro_ponto_id'), 'ponto_roteiro', ['ponto_id'], unique=False)
    op.create_index(op.f('ix_ponto_roteiro_roteiro_id'), 'ponto_roteiro', ['roteiro_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ponto_roteiro_roteiro_id'), table_name='ponto_roteiro')
    op.drop_index(op.f('ix_ponto_roteiro_ponto_id'), table_name='ponto_roteiro')
    op.drop_table('ponto_roteiro')
    op.drop_index('ix_roteiro_data_motorista', table_name='roteiro')
    op.drop_table('roteiro')
    op.drop_index(op.f('ix_motorista_gerente_id'), table_name='motorista')
    op.drop_table('motorista')
    op.drop_table('gerente')
    op.drop_index('ix_auditoria_entidade', table_name='auditoria')
    op.drop_index(op.f('ix_auditoria_criado_em'), table_name='auditoria')
    op.drop_table('auditoria')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('ponto')
    op.drop_table('parametro')
    # ### end Alembic commands ###
